// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: eta/booth/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9dc97f7edccd78de, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9dc97f7edccd78de, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryGetGuiltyVoteRequest struct {
	VoteId uint64 `protobuf:"varint,1,opt,name=voteId,proto3" json:"voteId,omitempty"`
}

func (m *QueryGetGuiltyVoteRequest) Reset()         { *m = QueryGetGuiltyVoteRequest{} }
func (m *QueryGetGuiltyVoteRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetGuiltyVoteRequest) ProtoMessage()    {}
func (*QueryGetGuiltyVoteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9dc97f7edccd78de, []int{2}
}
func (m *QueryGetGuiltyVoteRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetGuiltyVoteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetGuiltyVoteRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetGuiltyVoteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetGuiltyVoteRequest.Merge(m, src)
}
func (m *QueryGetGuiltyVoteRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetGuiltyVoteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetGuiltyVoteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetGuiltyVoteRequest proto.InternalMessageInfo

func (m *QueryGetGuiltyVoteRequest) GetVoteId() uint64 {
	if m != nil {
		return m.VoteId
	}
	return 0
}

type QueryGetGuiltyVoteResponse struct {
	GuiltyVote GuiltyVote `protobuf:"bytes,1,opt,name=guiltyVote,proto3" json:"guiltyVote"`
}

func (m *QueryGetGuiltyVoteResponse) Reset()         { *m = QueryGetGuiltyVoteResponse{} }
func (m *QueryGetGuiltyVoteResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetGuiltyVoteResponse) ProtoMessage()    {}
func (*QueryGetGuiltyVoteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9dc97f7edccd78de, []int{3}
}
func (m *QueryGetGuiltyVoteResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetGuiltyVoteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetGuiltyVoteResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetGuiltyVoteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetGuiltyVoteResponse.Merge(m, src)
}
func (m *QueryGetGuiltyVoteResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetGuiltyVoteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetGuiltyVoteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetGuiltyVoteResponse proto.InternalMessageInfo

func (m *QueryGetGuiltyVoteResponse) GetGuiltyVote() GuiltyVote {
	if m != nil {
		return m.GuiltyVote
	}
	return GuiltyVote{}
}

type QueryAllGuiltyVoteRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllGuiltyVoteRequest) Reset()         { *m = QueryAllGuiltyVoteRequest{} }
func (m *QueryAllGuiltyVoteRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllGuiltyVoteRequest) ProtoMessage()    {}
func (*QueryAllGuiltyVoteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9dc97f7edccd78de, []int{4}
}
func (m *QueryAllGuiltyVoteRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllGuiltyVoteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllGuiltyVoteRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllGuiltyVoteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllGuiltyVoteRequest.Merge(m, src)
}
func (m *QueryAllGuiltyVoteRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllGuiltyVoteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllGuiltyVoteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllGuiltyVoteRequest proto.InternalMessageInfo

func (m *QueryAllGuiltyVoteRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllGuiltyVoteResponse struct {
	GuiltyVote []GuiltyVote        `protobuf:"bytes,1,rep,name=guiltyVote,proto3" json:"guiltyVote"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllGuiltyVoteResponse) Reset()         { *m = QueryAllGuiltyVoteResponse{} }
func (m *QueryAllGuiltyVoteResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllGuiltyVoteResponse) ProtoMessage()    {}
func (*QueryAllGuiltyVoteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9dc97f7edccd78de, []int{5}
}
func (m *QueryAllGuiltyVoteResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllGuiltyVoteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllGuiltyVoteResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllGuiltyVoteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllGuiltyVoteResponse.Merge(m, src)
}
func (m *QueryAllGuiltyVoteResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllGuiltyVoteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllGuiltyVoteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllGuiltyVoteResponse proto.InternalMessageInfo

func (m *QueryAllGuiltyVoteResponse) GetGuiltyVote() []GuiltyVote {
	if m != nil {
		return m.GuiltyVote
	}
	return nil
}

func (m *QueryAllGuiltyVoteResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryGetPunishmentVoteRequest struct {
	VoteId uint64 `protobuf:"varint,1,opt,name=voteId,proto3" json:"voteId,omitempty"`
}

func (m *QueryGetPunishmentVoteRequest) Reset()         { *m = QueryGetPunishmentVoteRequest{} }
func (m *QueryGetPunishmentVoteRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetPunishmentVoteRequest) ProtoMessage()    {}
func (*QueryGetPunishmentVoteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9dc97f7edccd78de, []int{6}
}
func (m *QueryGetPunishmentVoteRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetPunishmentVoteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetPunishmentVoteRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetPunishmentVoteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetPunishmentVoteRequest.Merge(m, src)
}
func (m *QueryGetPunishmentVoteRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetPunishmentVoteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetPunishmentVoteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetPunishmentVoteRequest proto.InternalMessageInfo

func (m *QueryGetPunishmentVoteRequest) GetVoteId() uint64 {
	if m != nil {
		return m.VoteId
	}
	return 0
}

type QueryGetPunishmentVoteResponse struct {
	PunishmentVote PunishmentVote `protobuf:"bytes,1,opt,name=punishmentVote,proto3" json:"punishmentVote"`
}

func (m *QueryGetPunishmentVoteResponse) Reset()         { *m = QueryGetPunishmentVoteResponse{} }
func (m *QueryGetPunishmentVoteResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetPunishmentVoteResponse) ProtoMessage()    {}
func (*QueryGetPunishmentVoteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9dc97f7edccd78de, []int{7}
}
func (m *QueryGetPunishmentVoteResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetPunishmentVoteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetPunishmentVoteResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetPunishmentVoteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetPunishmentVoteResponse.Merge(m, src)
}
func (m *QueryGetPunishmentVoteResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetPunishmentVoteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetPunishmentVoteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetPunishmentVoteResponse proto.InternalMessageInfo

func (m *QueryGetPunishmentVoteResponse) GetPunishmentVote() PunishmentVote {
	if m != nil {
		return m.PunishmentVote
	}
	return PunishmentVote{}
}

type QueryAllPunishmentVoteRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllPunishmentVoteRequest) Reset()         { *m = QueryAllPunishmentVoteRequest{} }
func (m *QueryAllPunishmentVoteRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllPunishmentVoteRequest) ProtoMessage()    {}
func (*QueryAllPunishmentVoteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9dc97f7edccd78de, []int{8}
}
func (m *QueryAllPunishmentVoteRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllPunishmentVoteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllPunishmentVoteRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllPunishmentVoteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllPunishmentVoteRequest.Merge(m, src)
}
func (m *QueryAllPunishmentVoteRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllPunishmentVoteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllPunishmentVoteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllPunishmentVoteRequest proto.InternalMessageInfo

func (m *QueryAllPunishmentVoteRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllPunishmentVoteResponse struct {
	PunishmentVote []PunishmentVote    `protobuf:"bytes,1,rep,name=punishmentVote,proto3" json:"punishmentVote"`
	Pagination     *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllPunishmentVoteResponse) Reset()         { *m = QueryAllPunishmentVoteResponse{} }
func (m *QueryAllPunishmentVoteResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllPunishmentVoteResponse) ProtoMessage()    {}
func (*QueryAllPunishmentVoteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9dc97f7edccd78de, []int{9}
}
func (m *QueryAllPunishmentVoteResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllPunishmentVoteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllPunishmentVoteResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllPunishmentVoteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllPunishmentVoteResponse.Merge(m, src)
}
func (m *QueryAllPunishmentVoteResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllPunishmentVoteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllPunishmentVoteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllPunishmentVoteResponse proto.InternalMessageInfo

func (m *QueryAllPunishmentVoteResponse) GetPunishmentVote() []PunishmentVote {
	if m != nil {
		return m.PunishmentVote
	}
	return nil
}

func (m *QueryAllPunishmentVoteResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryGetPollRequest struct {
	PollId uint64 `protobuf:"varint,1,opt,name=pollId,proto3" json:"pollId,omitempty"`
}

func (m *QueryGetPollRequest) Reset()         { *m = QueryGetPollRequest{} }
func (m *QueryGetPollRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetPollRequest) ProtoMessage()    {}
func (*QueryGetPollRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9dc97f7edccd78de, []int{10}
}
func (m *QueryGetPollRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetPollRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetPollRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetPollRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetPollRequest.Merge(m, src)
}
func (m *QueryGetPollRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetPollRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetPollRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetPollRequest proto.InternalMessageInfo

func (m *QueryGetPollRequest) GetPollId() uint64 {
	if m != nil {
		return m.PollId
	}
	return 0
}

type QueryGetPollResponse struct {
	Poll Poll `protobuf:"bytes,1,opt,name=poll,proto3" json:"poll"`
}

func (m *QueryGetPollResponse) Reset()         { *m = QueryGetPollResponse{} }
func (m *QueryGetPollResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetPollResponse) ProtoMessage()    {}
func (*QueryGetPollResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9dc97f7edccd78de, []int{11}
}
func (m *QueryGetPollResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetPollResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetPollResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetPollResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetPollResponse.Merge(m, src)
}
func (m *QueryGetPollResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetPollResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetPollResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetPollResponse proto.InternalMessageInfo

func (m *QueryGetPollResponse) GetPoll() Poll {
	if m != nil {
		return m.Poll
	}
	return Poll{}
}

type QueryAllPollRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllPollRequest) Reset()         { *m = QueryAllPollRequest{} }
func (m *QueryAllPollRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllPollRequest) ProtoMessage()    {}
func (*QueryAllPollRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9dc97f7edccd78de, []int{12}
}
func (m *QueryAllPollRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllPollRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllPollRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllPollRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllPollRequest.Merge(m, src)
}
func (m *QueryAllPollRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllPollRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllPollRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllPollRequest proto.InternalMessageInfo

func (m *QueryAllPollRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllPollResponse struct {
	Poll       []Poll              `protobuf:"bytes,1,rep,name=poll,proto3" json:"poll"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllPollResponse) Reset()         { *m = QueryAllPollResponse{} }
func (m *QueryAllPollResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllPollResponse) ProtoMessage()    {}
func (*QueryAllPollResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9dc97f7edccd78de, []int{13}
}
func (m *QueryAllPollResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllPollResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllPollResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllPollResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllPollResponse.Merge(m, src)
}
func (m *QueryAllPollResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllPollResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllPollResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllPollResponse proto.InternalMessageInfo

func (m *QueryAllPollResponse) GetPoll() []Poll {
	if m != nil {
		return m.Poll
	}
	return nil
}

func (m *QueryAllPollResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "crowlabs.eta.booth.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "crowlabs.eta.booth.QueryParamsResponse")
	proto.RegisterType((*QueryGetGuiltyVoteRequest)(nil), "crowlabs.eta.booth.QueryGetGuiltyVoteRequest")
	proto.RegisterType((*QueryGetGuiltyVoteResponse)(nil), "crowlabs.eta.booth.QueryGetGuiltyVoteResponse")
	proto.RegisterType((*QueryAllGuiltyVoteRequest)(nil), "crowlabs.eta.booth.QueryAllGuiltyVoteRequest")
	proto.RegisterType((*QueryAllGuiltyVoteResponse)(nil), "crowlabs.eta.booth.QueryAllGuiltyVoteResponse")
	proto.RegisterType((*QueryGetPunishmentVoteRequest)(nil), "crowlabs.eta.booth.QueryGetPunishmentVoteRequest")
	proto.RegisterType((*QueryGetPunishmentVoteResponse)(nil), "crowlabs.eta.booth.QueryGetPunishmentVoteResponse")
	proto.RegisterType((*QueryAllPunishmentVoteRequest)(nil), "crowlabs.eta.booth.QueryAllPunishmentVoteRequest")
	proto.RegisterType((*QueryAllPunishmentVoteResponse)(nil), "crowlabs.eta.booth.QueryAllPunishmentVoteResponse")
	proto.RegisterType((*QueryGetPollRequest)(nil), "crowlabs.eta.booth.QueryGetPollRequest")
	proto.RegisterType((*QueryGetPollResponse)(nil), "crowlabs.eta.booth.QueryGetPollResponse")
	proto.RegisterType((*QueryAllPollRequest)(nil), "crowlabs.eta.booth.QueryAllPollRequest")
	proto.RegisterType((*QueryAllPollResponse)(nil), "crowlabs.eta.booth.QueryAllPollResponse")
}

func init() { proto.RegisterFile("eta/booth/query.proto", fileDescriptor_9dc97f7edccd78de) }

var fileDescriptor_9dc97f7edccd78de = []byte{
	// 778 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x96, 0x41, 0x6f, 0xd3, 0x4a,
	0x10, 0xc7, 0xe3, 0x36, 0x2f, 0xef, 0x69, 0x9f, 0x5e, 0xa5, 0xb7, 0x84, 0xaa, 0x75, 0xa9, 0x5b,
	0x96, 0x2a, 0x2d, 0x85, 0xd8, 0x4a, 0x2a, 0x04, 0x47, 0x52, 0x21, 0x2a, 0xb8, 0x10, 0x72, 0xe0,
	0x80, 0x84, 0x90, 0x13, 0x56, 0xae, 0xa5, 0x8d, 0xd7, 0x8d, 0x37, 0x85, 0xaa, 0x2a, 0x48, 0x48,
	0xdc, 0x91, 0x7a, 0xe1, 0xc4, 0xb9, 0x12, 0x12, 0x5f, 0x80, 0x2f, 0xd0, 0x63, 0x25, 0x2e, 0x9c,
	0x10, 0x6a, 0xf9, 0x20, 0xc8, 0xeb, 0x49, 0x6d, 0x27, 0x1b, 0x27, 0x85, 0xdc, 0x92, 0xf5, 0xfc,
	0x67, 0x7e, 0xff, 0x19, 0x7b, 0x6c, 0x74, 0x99, 0x0a, 0xdb, 0x6a, 0x72, 0x2e, 0xb6, 0xad, 0x9d,
	0x2e, 0xed, 0xec, 0x99, 0x7e, 0x87, 0x0b, 0x8e, 0x71, 0xab, 0xc3, 0x5f, 0x32, 0xbb, 0x19, 0x98,
	0x54, 0xd8, 0xa6, 0xbc, 0xae, 0x5f, 0x71, 0x38, 0x77, 0x18, 0xb5, 0x6c, 0xdf, 0xb5, 0x6c, 0xcf,
	0xe3, 0xc2, 0x16, 0x2e, 0xf7, 0x82, 0x48, 0xa1, 0xaf, 0xb7, 0x78, 0xd0, 0xe6, 0x81, 0xd5, 0xb4,
	0x03, 0x1a, 0xa5, 0xb2, 0x76, 0x2b, 0x4d, 0x2a, 0xec, 0x8a, 0xe5, 0xdb, 0x8e, 0xeb, 0xc9, 0x60,
	0x88, 0x9d, 0x8d, 0x8b, 0xfa, 0x76, 0xc7, 0x6e, 0xf7, 0x72, 0x2c, 0xc4, 0xe7, 0x4e, 0xd7, 0x65,
	0x62, 0xef, 0xf9, 0x2e, 0x17, 0x14, 0x2e, 0x2e, 0x25, 0x44, 0x5d, 0xcf, 0x0d, 0xb6, 0xdb, 0xd4,
	0x13, 0xc9, 0x80, 0x62, 0x22, 0x80, 0x33, 0x06, 0xa7, 0x46, 0x92, 0xab, 0x47, 0xd4, 0xe2, 0x6e,
	0x8f, 0xa5, 0xe8, 0x70, 0x87, 0xcb, 0x9f, 0x56, 0xf8, 0x2b, 0x3a, 0x25, 0x45, 0x84, 0x1f, 0x87,
	0x1e, 0xea, 0x12, 0xaf, 0x41, 0x77, 0xba, 0x34, 0x10, 0xe4, 0x11, 0xba, 0x94, 0x3a, 0x0d, 0x7c,
	0xee, 0x05, 0x14, 0xdf, 0x41, 0x85, 0xc8, 0xc6, 0x9c, 0xb6, 0xac, 0xad, 0xfd, 0x5b, 0xd5, 0xcd,
	0xc1, 0xee, 0x99, 0x91, 0x66, 0x33, 0x7f, 0xfc, 0x7d, 0x29, 0xd7, 0x80, 0x78, 0xb2, 0x81, 0xe6,
	0x65, 0xc2, 0x2d, 0x2a, 0xb6, 0xa4, 0xe1, 0x27, 0x5c, 0x50, 0xa8, 0x86, 0x67, 0x51, 0x21, 0x74,
	0xf7, 0xe0, 0x85, 0x4c, 0x9b, 0x6f, 0xc0, 0x3f, 0xd2, 0x44, 0xba, 0x4a, 0x04, 0x30, 0xf7, 0x10,
	0x72, 0xce, 0x4f, 0x01, 0xc8, 0x50, 0x01, 0xc5, 0x5a, 0x80, 0x4a, 0xe8, 0x48, 0x0b, 0xc0, 0x6a,
	0x8c, 0x0d, 0x82, 0xdd, 0x47, 0x28, 0x1e, 0x29, 0x94, 0x28, 0x99, 0x51, 0x9f, 0xcd, 0xb0, 0xcf,
	0x66, 0x74, 0x2b, 0x41, 0xb7, 0xcd, 0xba, 0xed, 0xf4, 0xb4, 0x8d, 0x84, 0x92, 0x7c, 0xd2, 0xc0,
	0x49, 0x5f, 0x95, 0x21, 0x4e, 0xa6, 0x7f, 0xc7, 0x09, 0xde, 0x4a, 0xc1, 0x4e, 0x49, 0xd8, 0xd5,
	0x91, 0xb0, 0x11, 0x42, 0x8a, 0xf6, 0x36, 0x5a, 0xec, 0xb5, 0xbd, 0x7e, 0x7e, 0xff, 0x8d, 0x33,
	0xaf, 0x0e, 0x32, 0x86, 0x09, 0xc1, 0x69, 0x1d, 0xcd, 0xf8, 0xa9, 0x2b, 0xd0, 0x54, 0xa2, 0xbc,
	0x91, 0x52, 0x91, 0xe0, 0xb8, 0x4f, 0x4f, 0x1c, 0x80, 0xad, 0x31, 0xa6, 0x86, 0x9d, 0xd4, 0x0c,
	0xbf, 0x68, 0xe0, 0x4e, 0x51, 0x29, 0xc3, 0xdd, 0xf4, 0x9f, 0xb8, 0x9b, 0xdc, 0x4c, 0xcb, 0xf0,
	0x40, 0x87, 0xa3, 0xe1, 0x8c, 0x25, 0x26, 0x19, 0x6e, 0x90, 0x78, 0x92, 0xd1, 0x3f, 0xf2, 0x10,
	0x15, 0xd3, 0xe1, 0xe0, 0xb0, 0x8a, 0xf2, 0x61, 0x04, 0xb4, 0x71, 0x4e, 0xe9, 0x8b, 0x33, 0x06,
	0x6e, 0x64, 0x2c, 0x79, 0x06, 0xa5, 0xc3, 0xbe, 0x25, 0x4a, 0x4f, 0x6a, 0x2e, 0x87, 0x1a, 0xb0,
	0x9e, 0xe7, 0x1f, 0x60, 0x9d, 0x1e, 0x97, 0x75, 0x62, 0xfd, 0xae, 0x1e, 0xfd, 0x83, 0xfe, 0x92,
	0x54, 0xf8, 0x35, 0x2a, 0x44, 0x1b, 0x11, 0x97, 0x54, 0x08, 0x83, 0xcb, 0x57, 0x5f, 0x1d, 0x19,
	0x17, 0x15, 0x24, 0xd7, 0xde, 0x7e, 0xfd, 0x79, 0x38, 0xb5, 0x88, 0x17, 0xac, 0x50, 0x50, 0x0e,
	0x15, 0x56, 0xff, 0x0b, 0x07, 0x7f, 0xd4, 0x10, 0x8a, 0xf7, 0x06, 0x2e, 0x0f, 0x4d, 0xae, 0x5a,
	0xcd, 0xba, 0x39, 0x6e, 0x38, 0x20, 0x55, 0x24, 0xd2, 0x0d, 0x7c, 0x5d, 0x89, 0x94, 0x78, 0xd7,
	0x59, 0xfb, 0xd1, 0xd2, 0x38, 0xc0, 0x1f, 0x34, 0xf4, 0x5f, 0x9c, 0xa9, 0xc6, 0x58, 0x06, 0xa3,
	0x6a, 0x4b, 0x67, 0x30, 0x2a, 0xd7, 0x2d, 0x59, 0x93, 0x8c, 0x04, 0x2f, 0x8f, 0x62, 0xc4, 0x9f,
	0x35, 0x34, 0x93, 0x7e, 0x4e, 0x71, 0x25, 0xab, 0x21, 0xca, 0x0d, 0xa4, 0x57, 0x2f, 0x22, 0x01,
	0xc6, 0x5b, 0x92, 0xd1, 0xc2, 0x65, 0xf5, 0x68, 0xd3, 0x9f, 0x05, 0x71, 0x2f, 0x8f, 0x34, 0xf4,
	0x7f, 0x3a, 0x63, 0xd8, 0xcf, 0x4a, 0x56, 0x83, 0x2e, 0xca, 0x3c, 0x74, 0xfd, 0x91, 0x9b, 0x92,
	0xb9, 0x84, 0x57, 0xc6, 0x61, 0xc6, 0xef, 0x34, 0x94, 0x0f, 0x9f, 0x3f, 0xbc, 0x9a, 0xd9, 0x9e,
	0x78, 0x63, 0xe8, 0x6b, 0xa3, 0x03, 0x81, 0x64, 0x5d, 0x92, 0xac, 0x60, 0xa2, 0x26, 0xe1, 0x8c,
	0x59, 0xfb, 0xd1, 0xa6, 0x3b, 0xc0, 0x6f, 0xd0, 0xdf, 0xa1, 0xb6, 0x96, 0x49, 0x92, 0xde, 0x5d,
	0x19, 0x24, 0x7d, 0x4b, 0x88, 0x5c, 0x95, 0x24, 0x0b, 0x78, 0x7e, 0x28, 0xc9, 0xe6, 0xdd, 0xe3,
	0x53, 0x43, 0x3b, 0x39, 0x35, 0xb4, 0x1f, 0xa7, 0x86, 0xf6, 0xfe, 0xcc, 0xc8, 0x9d, 0x9c, 0x19,
	0xb9, 0x6f, 0x67, 0x46, 0xee, 0x69, 0xc9, 0x71, 0xc5, 0x76, 0xb7, 0x69, 0xb6, 0x78, 0xbb, 0x4f,
	0xfe, 0x0a, 0x12, 0x88, 0x3d, 0x9f, 0x06, 0xcd, 0x82, 0xfc, 0x94, 0xdb, 0xf8, 0x15, 0x00, 0x00,
	0xff, 0xff, 0x2d, 0xc6, 0x73, 0x35, 0xe3, 0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a GuiltyVote by index.
	GuiltyVote(ctx context.Context, in *QueryGetGuiltyVoteRequest, opts ...grpc.CallOption) (*QueryGetGuiltyVoteResponse, error)
	// Queries a list of GuiltyVote items.
	GuiltyVoteAll(ctx context.Context, in *QueryAllGuiltyVoteRequest, opts ...grpc.CallOption) (*QueryAllGuiltyVoteResponse, error)
	// Queries a PunishmentVote by index.
	PunishmentVote(ctx context.Context, in *QueryGetPunishmentVoteRequest, opts ...grpc.CallOption) (*QueryGetPunishmentVoteResponse, error)
	// Queries a list of PunishmentVote items.
	PunishmentVoteAll(ctx context.Context, in *QueryAllPunishmentVoteRequest, opts ...grpc.CallOption) (*QueryAllPunishmentVoteResponse, error)
	// Queries a Poll by index.
	Poll(ctx context.Context, in *QueryGetPollRequest, opts ...grpc.CallOption) (*QueryGetPollResponse, error)
	// Queries a list of Poll items.
	PollAll(ctx context.Context, in *QueryAllPollRequest, opts ...grpc.CallOption) (*QueryAllPollResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/crowlabs.eta.booth.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GuiltyVote(ctx context.Context, in *QueryGetGuiltyVoteRequest, opts ...grpc.CallOption) (*QueryGetGuiltyVoteResponse, error) {
	out := new(QueryGetGuiltyVoteResponse)
	err := c.cc.Invoke(ctx, "/crowlabs.eta.booth.Query/GuiltyVote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GuiltyVoteAll(ctx context.Context, in *QueryAllGuiltyVoteRequest, opts ...grpc.CallOption) (*QueryAllGuiltyVoteResponse, error) {
	out := new(QueryAllGuiltyVoteResponse)
	err := c.cc.Invoke(ctx, "/crowlabs.eta.booth.Query/GuiltyVoteAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) PunishmentVote(ctx context.Context, in *QueryGetPunishmentVoteRequest, opts ...grpc.CallOption) (*QueryGetPunishmentVoteResponse, error) {
	out := new(QueryGetPunishmentVoteResponse)
	err := c.cc.Invoke(ctx, "/crowlabs.eta.booth.Query/PunishmentVote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) PunishmentVoteAll(ctx context.Context, in *QueryAllPunishmentVoteRequest, opts ...grpc.CallOption) (*QueryAllPunishmentVoteResponse, error) {
	out := new(QueryAllPunishmentVoteResponse)
	err := c.cc.Invoke(ctx, "/crowlabs.eta.booth.Query/PunishmentVoteAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Poll(ctx context.Context, in *QueryGetPollRequest, opts ...grpc.CallOption) (*QueryGetPollResponse, error) {
	out := new(QueryGetPollResponse)
	err := c.cc.Invoke(ctx, "/crowlabs.eta.booth.Query/Poll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) PollAll(ctx context.Context, in *QueryAllPollRequest, opts ...grpc.CallOption) (*QueryAllPollResponse, error) {
	out := new(QueryAllPollResponse)
	err := c.cc.Invoke(ctx, "/crowlabs.eta.booth.Query/PollAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a GuiltyVote by index.
	GuiltyVote(context.Context, *QueryGetGuiltyVoteRequest) (*QueryGetGuiltyVoteResponse, error)
	// Queries a list of GuiltyVote items.
	GuiltyVoteAll(context.Context, *QueryAllGuiltyVoteRequest) (*QueryAllGuiltyVoteResponse, error)
	// Queries a PunishmentVote by index.
	PunishmentVote(context.Context, *QueryGetPunishmentVoteRequest) (*QueryGetPunishmentVoteResponse, error)
	// Queries a list of PunishmentVote items.
	PunishmentVoteAll(context.Context, *QueryAllPunishmentVoteRequest) (*QueryAllPunishmentVoteResponse, error)
	// Queries a Poll by index.
	Poll(context.Context, *QueryGetPollRequest) (*QueryGetPollResponse, error)
	// Queries a list of Poll items.
	PollAll(context.Context, *QueryAllPollRequest) (*QueryAllPollResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) GuiltyVote(ctx context.Context, req *QueryGetGuiltyVoteRequest) (*QueryGetGuiltyVoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GuiltyVote not implemented")
}
func (*UnimplementedQueryServer) GuiltyVoteAll(ctx context.Context, req *QueryAllGuiltyVoteRequest) (*QueryAllGuiltyVoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GuiltyVoteAll not implemented")
}
func (*UnimplementedQueryServer) PunishmentVote(ctx context.Context, req *QueryGetPunishmentVoteRequest) (*QueryGetPunishmentVoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PunishmentVote not implemented")
}
func (*UnimplementedQueryServer) PunishmentVoteAll(ctx context.Context, req *QueryAllPunishmentVoteRequest) (*QueryAllPunishmentVoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PunishmentVoteAll not implemented")
}
func (*UnimplementedQueryServer) Poll(ctx context.Context, req *QueryGetPollRequest) (*QueryGetPollResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Poll not implemented")
}
func (*UnimplementedQueryServer) PollAll(ctx context.Context, req *QueryAllPollRequest) (*QueryAllPollResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PollAll not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/crowlabs.eta.booth.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GuiltyVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetGuiltyVoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GuiltyVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/crowlabs.eta.booth.Query/GuiltyVote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GuiltyVote(ctx, req.(*QueryGetGuiltyVoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GuiltyVoteAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllGuiltyVoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GuiltyVoteAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/crowlabs.eta.booth.Query/GuiltyVoteAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GuiltyVoteAll(ctx, req.(*QueryAllGuiltyVoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_PunishmentVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetPunishmentVoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).PunishmentVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/crowlabs.eta.booth.Query/PunishmentVote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).PunishmentVote(ctx, req.(*QueryGetPunishmentVoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_PunishmentVoteAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllPunishmentVoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).PunishmentVoteAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/crowlabs.eta.booth.Query/PunishmentVoteAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).PunishmentVoteAll(ctx, req.(*QueryAllPunishmentVoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Poll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetPollRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Poll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/crowlabs.eta.booth.Query/Poll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Poll(ctx, req.(*QueryGetPollRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_PollAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllPollRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).PollAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/crowlabs.eta.booth.Query/PollAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).PollAll(ctx, req.(*QueryAllPollRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "crowlabs.eta.booth.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "GuiltyVote",
			Handler:    _Query_GuiltyVote_Handler,
		},
		{
			MethodName: "GuiltyVoteAll",
			Handler:    _Query_GuiltyVoteAll_Handler,
		},
		{
			MethodName: "PunishmentVote",
			Handler:    _Query_PunishmentVote_Handler,
		},
		{
			MethodName: "PunishmentVoteAll",
			Handler:    _Query_PunishmentVoteAll_Handler,
		},
		{
			MethodName: "Poll",
			Handler:    _Query_Poll_Handler,
		},
		{
			MethodName: "PollAll",
			Handler:    _Query_PollAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "eta/booth/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetGuiltyVoteRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetGuiltyVoteRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetGuiltyVoteRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.VoteId != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.VoteId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetGuiltyVoteResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetGuiltyVoteResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetGuiltyVoteResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.GuiltyVote.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllGuiltyVoteRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllGuiltyVoteRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllGuiltyVoteRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllGuiltyVoteResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllGuiltyVoteResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllGuiltyVoteResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.GuiltyVote) > 0 {
		for iNdEx := len(m.GuiltyVote) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.GuiltyVote[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetPunishmentVoteRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetPunishmentVoteRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetPunishmentVoteRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.VoteId != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.VoteId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetPunishmentVoteResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetPunishmentVoteResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetPunishmentVoteResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.PunishmentVote.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllPunishmentVoteRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllPunishmentVoteRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllPunishmentVoteRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllPunishmentVoteResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllPunishmentVoteResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllPunishmentVoteResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.PunishmentVote) > 0 {
		for iNdEx := len(m.PunishmentVote) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PunishmentVote[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetPollRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetPollRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetPollRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.PollId != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.PollId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetPollResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetPollResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetPollResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Poll.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllPollRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllPollRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllPollRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllPollResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllPollResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllPollResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Poll) > 0 {
		for iNdEx := len(m.Poll) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Poll[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetGuiltyVoteRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.VoteId != 0 {
		n += 1 + sovQuery(uint64(m.VoteId))
	}
	return n
}

func (m *QueryGetGuiltyVoteResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.GuiltyVote.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllGuiltyVoteRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllGuiltyVoteResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.GuiltyVote) > 0 {
		for _, e := range m.GuiltyVote {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetPunishmentVoteRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.VoteId != 0 {
		n += 1 + sovQuery(uint64(m.VoteId))
	}
	return n
}

func (m *QueryGetPunishmentVoteResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.PunishmentVote.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllPunishmentVoteRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllPunishmentVoteResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.PunishmentVote) > 0 {
		for _, e := range m.PunishmentVote {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetPollRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.PollId != 0 {
		n += 1 + sovQuery(uint64(m.PollId))
	}
	return n
}

func (m *QueryGetPollResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Poll.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllPollRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllPollResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Poll) > 0 {
		for _, e := range m.Poll {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetGuiltyVoteRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetGuiltyVoteRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetGuiltyVoteRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VoteId", wireType)
			}
			m.VoteId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VoteId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetGuiltyVoteResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetGuiltyVoteResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetGuiltyVoteResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GuiltyVote", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.GuiltyVote.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllGuiltyVoteRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllGuiltyVoteRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllGuiltyVoteRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllGuiltyVoteResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllGuiltyVoteResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllGuiltyVoteResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GuiltyVote", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GuiltyVote = append(m.GuiltyVote, GuiltyVote{})
			if err := m.GuiltyVote[len(m.GuiltyVote)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetPunishmentVoteRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetPunishmentVoteRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetPunishmentVoteRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VoteId", wireType)
			}
			m.VoteId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VoteId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetPunishmentVoteResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetPunishmentVoteResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetPunishmentVoteResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PunishmentVote", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.PunishmentVote.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllPunishmentVoteRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllPunishmentVoteRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllPunishmentVoteRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllPunishmentVoteResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllPunishmentVoteResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllPunishmentVoteResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PunishmentVote", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PunishmentVote = append(m.PunishmentVote, PunishmentVote{})
			if err := m.PunishmentVote[len(m.PunishmentVote)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetPollRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetPollRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetPollRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PollId", wireType)
			}
			m.PollId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PollId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetPollResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetPollResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetPollResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Poll", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Poll.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllPollRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllPollRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllPollRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllPollResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllPollResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllPollResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Poll", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Poll = append(m.Poll, Poll{})
			if err := m.Poll[len(m.Poll)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
